name: opinion.works
title: 孙建康
email: rising.lambda@gmail.com
description: 软件开发/全桟工程师
baseurl:  # the subpath of your site, e.g. /blog
url: https://opinion.works # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
  - jekyll-paginate

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /posts/:year/:month/:day/:title/

about:
  owner:
    name: 孙建康
    github:
      uri: https://github.com/sjkyspa
